from typing import Dict, Any

def to_markdown_report(deal_package: Dict[str, Any]) -> str:
    p = deal_package["property"]
    a = deal_package["assumptions"]
    s = deal_package["scenarios"]

    def line(k: str, v: Any) -> str:
        return f"- **{k}**: {v}"

    base = s["base"]

    md = []
    md.append("# AXIOM Deal Report")
    md.append("")
    md.append("## Property")
    md.append(line("ID", p.get("id")))
    md.append(line("Address", f"{p.get('address')}, {p.get('city')}, {p.get('state')} {p.get('zip')}"))
    md.append(line("Asset Class", p.get("asset_class")))
    md.append(line("Square Footage", p.get("sqft")))
    md.append(line("Ask Price", p.get("ask_price")))
    md.append(line("NOI Year 1", p.get("noi_year1")))
    md.append("")
    md.append("## Assumptions")
    md.append(line("LTC", a.get("ltc")))
    md.append(line("Interest Rate", a.get("interest_rate")))
    md.append(line("Amort Years", a.get("amort_years")))
    md.append(line("Hold Years", a.get("hold_years")))
    md.append(line("NOI Growth", a.get("noi_growth")))
    md.append(line("Exit Cap", a.get("exit_cap_rate")))
    md.append(line("Sale Costs", a.get("sale_cost_pct")))
    md.append(line("Capex Override", a.get("capex_override")))
    md.append(line("Vacancy Override", a.get("vacancy_override")))
    md.append("")
    md.append("## Base Case Results")
    md.append(line("IRR", base.get("irr")))
    md.append(line("Cash-on-Cash (Y1)", base.get("cash_on_cash_year1")))
    md.append(line("DSCR (Y1)", base.get("dscr_year1")))
    md.append(line("Equity Multiple", base.get("equity_multiple")))
    md.append(line("Sale Price Est.", base.get("sale_price_est")))
    md.append(line("Net Sale to Equity Est.", base.get("net_sale_to_equity_est")))
    md.append("")
    md.append("## Scenario Table")
    md.append("")
    md.append("| Scenario | IRR | CoC (Y1) | DSCR (Y1) | Equity Multiple | Sale Price |")
    md.append("|---|---:|---:|---:|---:|---:|")
    for name, vals in s.items():
        md.append(f"| {name} | {vals.get('irr')} | {vals.get('cash_on_cash_year1')} | {vals.get('dscr_year1')} | {vals.get('equity_multiple')} | {vals.get('sale_price_est')} |")

    md.append("")
    md.append("## Notes")
    md.append("- Generated by AXIOM Shared Engine (Juniper Rose).")
    return "\n".join(md)
